#!/bin/bash

cp -ru home/.* $HOME/.

cp -ru $HOME/.zsh home/.
cp -ru $HOME/.zshrc home/.
cp -ru $HOME/.condarc home/.
cp -ru $HOME/.gitconfig home/.
cp -ru $HOME/.tmux.conf home/.

cp -ru $HOME/.config/nvim home/.config/.
cp -ru $HOME/.config/htop home/.config/.
cp -ru $HOME/.config/starship.toml home/.config/.

cp -ru $HOME/.local/bin/frm home/.local/bin/.
cp -ru $HOME/.local/bin/gpull home/.local/bin/.

